matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
git:
  submodules: false
before_install:
    - mkdir -p latest-gcc-symlinks
    - ln -s /usr/bin/g++-7 latest-gcc-symlinks/g++
    - ln -s /usr/bin/gcc-7 latest-gcc-symlinks/gcc
    - export PATH=$PWD/latest-gcc-symlinks:$PATH
    - eval "${MATRIX_EVAL}"
    - g++ --version
    - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
    - sudo apt-get update && sudo apt-get install bazel
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init 

script:
    - bazel build ...
    #- bazel test ... --test_output=all

after_failure:
    - cat bazel-out/k8-fastbuild/testlogs/hello-test/test.log


