matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"



before_install:
    - wget https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel_0.3.1-linux-x86_64.deb
    - sha256sum -c tools/bazel_0.3.1-linux-x86_64.deb.sha256
    - sudo dpkg -i bazel_0.3.1-linux-x86_64.deb

script:
    - bazel test ...


